version: '3.1'
services:
  backend:
    container_name: spring_docker_final_project
    image: docker-springboot-final-project
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - "PostgreSQL"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/postgres2
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  PostgreSQL:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sa
      - POSTGRES_DB=postgres2
